import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
await page.goto('http://localhost:4173/', { waitUntil: 'networkidle' });
await page.waitForTimeout(3000);
const at = async () => page.evaluate(() => window.__brainDebug ? {p: +window.__brainDebug.p.toFixed(3), deg: +(window.__brainDebug.rotY*180/Math.PI).toFixed(1)} : null);
console.log('top:', await at());
await page.evaluate(() => document.querySelector('#how-it-works').scrollIntoView({behavior:'instant'}));
await page.waitForTimeout(1500);
console.log('how-it-works:', await at());
await page.evaluate(() => document.querySelector('.home-final-cta').scrollIntoView({behavior:'instant', block:'center'}));
await page.waitForTimeout(2000);
console.log('CTA:', await at());
await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
await page.waitForTimeout(1500);
console.log('bottom (should hold ~-90):', await at());
await page.evaluate(() => window.scrollTo(0, 0));
await page.waitForTimeout(2000);
console.log('back to top (should return ~0):', await at());
await browser.close();
